<?php

namespace Database\Seeders;

use App\Models\Apartment;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ApartmentSeeder extends Seeder
{
    public function run()
    {

        $apartmentsData=[


            [
                'Nome' => 'Appartamento Milano',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 75,
                'Prezzo' => 100,
                'Indirizzo' => 'Via Giovanni Boccaccio, 12, Cologno Monzese, MI, Italia',
                'Latitudine' => 45.46368,
                'Longitudine' => 9.18841,
                'Img' => "https://media.istockphoto.com/id/1357529933/it/foto/immagine-generata-digitalmente-di-un-soggiorno-completamente-arredato.jpg?s=612x612&w=0&k=20&c=KFDbMAwKoWcGU55-S2u6_BLF-7o-E4H1MBKnTnEI6Qc=",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Napoli',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 100,
                'Prezzo' => 120,
                'Indirizzo' => 'Via Toledo, Via dei Tribunali, Napoli, NA, Italia',
                'Latitudine' => 40.851798,
                'Longitudine' => 14.26812,
                'Img' => "https://st.hzcdn.com/simgs/pictures/soggiorni/home-staging-appartamento-vuoto-in-vendita-micro-interior-design-img~503160220ccd6834_4-8587-1-f5ce958.jpg",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Firenze',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 60,
                'Prezzo' => 90,
                'Indirizzo' => 'Via Palagio degli Spini, Firenze, FI, Italia',
                'Latitudine' => 43.769871,
                'Longitudine' => 11.255576,
                'Img' => "https://media.istockphoto.com/id/1365110240/it/foto/interni-in-stile-boho-arancione-con-poltrona-com%C3%B2-e-decorazione-mockup-di-illustrazione-di.jpg?s=612x612&w=0&k=20&c=e_4kJPBbxPJ7Bb8_aDzc2vurt0VToLftTqz0eBW-LSY=",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Torino',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 150,
                'Prezzo' => 150,
                'Indirizzo' => 'Via Giuseppe Garibaldi, Torino, TO, Italia',
                'Latitudine' => 45.070339,
                'Longitudine' => 7.686864,
                'Img' => "https://media.istockphoto.com/id/1372682941/it/foto/parete-verde-verticale-allinterno-di-un-soggiorno-rendering-3d.jpg?s=612x612&w=0&k=20&c=a9yRLlsku9cVrezOR4zez6XZX5E-HwTbRboxidu3oG8=",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Roma',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 2,
                'Metri_quadrati' => 85,
                'Prezzo' => 110,
                'Indirizzo' => 'Via Appia Antica, Roma RM, Italia',
                'Latitudine' => 41.902784,
                'Longitudine' => 12.496366,
                'Img' => 'https://media.istockphoto.com/id/1335582229/it/video/timelapse-dellanimazione-di-rendering-3d-casa-interna-moderno-spazio-abitativo-aperto-con.jpg?s=640x640&k=20&c=4s2SXACCRklcZWQDfs8BhVw0uZYKN0Y4QchRIzQG4i0=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Genova',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 55,
                'Prezzo' => 85,
                'Indirizzo' => 'Via XX Settembre, Genova, GE, Italia',
                'Latitudine' => 44.407062,
                'Longitudine' => 8.93399,
                'Img' => "https://media.istockphoto.com/id/1426549872/it/foto/ampio-soggiorno-moderno-e-lussuoso-rendering-interno-in-3d.jpg?s=612x612&w=0&k=20&c=6fScIpsGypRY2siqsK34nI5TXunmQv_ER4N1slDyWFg=",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Venezia',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 120,
                'Prezzo' => 200,
                'Indirizzo' => 'Via Santa Lucia, Venezia, VE, Italia',
                'Latitudine' => 45.434046,
                'Longitudine' => 12.338166,
                'Img' => "https://media.istockphoto.com/id/1490571644/it/foto/immagine-generata-digitalmente-di-un-soggiorno-con-pavimento-in-legno.jpg?s=612x612&w=0&k=20&c=UvDcPMAu95wVeV7YQHRm8ADZx6OZEcI6RX4bQwVObiA=",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Palermo',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 70,
                'Prezzo' => 80,
                'Indirizzo' => 'Via Maqueda, Palermo, PA, Italia',
                'Latitudine' => 38.115697,
                'Longitudine' => 13.361267,
                'Img' => "https://media.istockphoto.com/id/1425142559/it/foto/rendering-3d-di-un-interno-di-casa-moderno.jpg?s=612x612&w=0&k=20&c=EfaerKNDFbqknEAMKX_xh3AjN4UvibWz0PfOMgywM5M=",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Bari',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 2,
                'Metri_quadrati' => 95,
                'Prezzo' => 95,
                'Indirizzo' => 'Via Giuseppe Capruzzi, Bari BA, Italia',
                'Latitudine' => 41.125594,
                'Longitudine' => 16.866067,
                'Img' => "https://media.istockphoto.com/id/1366921254/it/foto/interior-design-di-soggiorno-colorato-concetto-interno-di-design-memphis-rendering-3d.jpg?s=612x612&w=0&k=20&c=V5SjExBJhuN5BDtKcfkhmu3GsIqYTSPxnI-lhendLp0=",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Verona',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 160,
                'Prezzo' => 180,
                'Indirizzo' => 'Via del Pestrino, Verona, Italia',
                'Latitudine' => 45.438759,
                'Longitudine' => 10.99162,
                'Img' => "https://media.istockphoto.com/id/1353803182/it/foto/elegante-composizione-di-interni-del-soggiorno-con-cornice-mock-up-panca-in-legno-cuscino.jpg?s=612x612&w=0&k=20&c=M_jd2tNKYhnJ8chSJE9iSoguKmGbSAGM9Xt674Vs-e8=",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Marco',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 120,
                'Prezzo' => 180,
                'Indirizzo' => 'Via della Libertà, Palermo, Italia',
                'Latitudine' => 38.12445,
                'Longitudine' => 13.35732,
                'Img' => 'https://media.istockphoto.com/id/1316508805/it/foto/rendering-3d-degli-interni-moderni-del-soggiorno.jpg?s=612x612&w=0&k=20&c=AlsXo9jM2_8Czy12Ep3e16K6LJLpKnJvNwOBYAfxrf0=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Alessandra',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 85,
                'Prezzo' => 160,
                'Indirizzo' => 'Via del Corso, Roma, Italia',
                'Latitudine' => 41.902783,
                'Longitudine' => 12.496366,
                'Img' => 'https://media.istockphoto.com/id/2159352095/it/foto/interno-del-soggiorno-vecchio-stile-con-una-libreria-in-3d.jpg?s=612x612&w=0&k=20&c=se9WGmWvqF-ZrcKt2iNNR_uAijZTXTCXRR4mLDsoVtk=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Attico Aurora',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 180,
                'Prezzo' => 270,
                'Indirizzo' => 'Via Torino, Milano, Italia',
                'Latitudine' => 45.464211,
                'Longitudine' => 9.191383,
                'Img' => 'https://media.istockphoto.com/id/1977204395/it/foto/immagine-digitale-di-un-bellissimo-soggiorno-di-una-grande-casa-in-stile-vittoriano.jpg?s=612x612&w=0&k=20&c=eVMyVU23ShS4QczICvvdyDEpqZNqENrHgGB32skn7JQ=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Arcobaleno',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 250,
                'Prezzo' => 350,
                'Indirizzo' => 'Via Garibaldi, Venezia, Italia',
                'Latitudine' => 45.437191,
                'Longitudine' => 12.334589,
                'Img' => 'https://media.istockphoto.com/id/1423139126/it/foto/interni-minimalisti-contemporanei-neri-con-divano-e-decorazioni-mockup-dellillustrazione-di.jpg?s=612x612&w=0&k=20&c=3aEVLN00BnjwoUe8DcLat0QB3_JB-6vBN44jQG8W8L0=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Luca',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 95,
                'Prezzo' => 140,
                'Indirizzo' => 'Via XX Settembre, Genova, Italia',
                'Latitudine' => 44.40564,
                'Longitudine' => 8.946256,
                'Img' => 'https://media.istockphoto.com/id/1351070483/it/foto/composizione-creativa-di-eleganti-interni-del-soggiorno-con-cornice-per-poster-mock-up-divano.jpg?s=612x612&w=0&k=20&c=LHPUehWom4s56g3ZtL7RbXhBnjLLcqNV4JHX3zXt7z4=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa Sole',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 110,
                'Prezzo' => 210,
                'Indirizzo' => 'Via Roma, Cagliari, Italia',
                'Latitudine' => 39.223841,
                'Longitudine' => 9.121661,
                'Img' => 'https://media.istockphoto.com/id/1217965465/it/foto/classico-interno-nero-loft-con-pannello-in-legno-divano-chesterfield-tappeto-fiori-tavolino-e.jpg?s=612x612&w=0&k=20&c=tAMV2OS5flhfM8pbVUrLiD7PbDyu8yB8E4M18O-qbkE=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Gaia',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 70,
                'Prezzo' => 120,
                'Indirizzo' => 'Via Dante, Bari, Italia',
                'Latitudine' => 41.117143,
                'Longitudine' => 16.871871,
                'Img' => 'https://media.istockphoto.com/id/1316453848/it/foto/interno-della-camera-nera-con-divano-in-velluto-verde-pavimento-in-legno-moquette-e.jpg?s=612x612&w=0&k=20&c=MsrOpLHy_otS_HkOcRAhf8eEnQhvbxwH5UJ_q45LfjI=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Loft Stella',
                'Stanze' => 1,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 60,
                'Prezzo' => 130,
                'Indirizzo' => 'Via Mazzini, Torino, Italia',
                'Latitudine' => 45.070312,
                'Longitudine' => 7.686856,
                'Img' => 'https://media.istockphoto.com/id/1460051694/it/foto/interior-design-di-appartamento-moderno-mockup-interno-rendering-3d.jpg?s=612x612&w=0&k=20&c=RpT7N6tFF2XeECN5p7nuBKuWT3rBiC8S5-xn6nyj7g8=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Federico',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 125,
                'Prezzo' => 230,
                'Indirizzo' => 'Piazza San Marco, Venezia, Italia',
                'Latitudine' => 45.434095,
                'Longitudine' => 12.338844,
                'Img' => 'https://media.istockphoto.com/id/1402804806/it/foto/rendering-3d-illustrazione-3d-mockup-di-scena-interna-e-cornice-angolo-cottura-a-forma-di-l.jpg?s=612x612&w=0&k=20&c=qsfpVNvv6IiiRkaaxDTKsxrzZaak0Y-1jxkSJrz-PsQ=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Attico di Martina',
                'Stanze' => 6,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 200,
                'Prezzo' => 320,
                'Indirizzo' => 'Via San Lorenzo, Firenze, Italia',
                'Latitudine' => 43.76956,
                'Longitudine' => 11.255814,
                'Img' => 'https://media.istockphoto.com/id/1425142484/it/foto/rendering-3d-di-un-lussuoso-design-della-sala-da-pranzo.jpg?s=612x612&w=0&k=20&c=tKv1d7mG2Cac3agVGyLoTb1KjGBZctggwNOfSTdmWXI=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Luna',
                'Stanze' => 7,
                'Letti' => 6,
                'Bagni' => 5,
                'Metri_quadrati' => 300,
                'Prezzo' => 450,
                'Indirizzo' => 'Via Vittorio Emanuele, Palermo, Italia',
                'Latitudine' => 38.115687,
                'Longitudine' => 13.361267,
                'Img' => 'https://media.istockphoto.com/id/1384261771/it/foto/elegante-design-degli-interni-del-soggiorno-con-cornice-del-poster-mockup-moderna-poltrona.jpg?s=612x612&w=0&k=20&c=tbbK9DxhDBgkZr4K_hvnx7gJnZGrEXoTLJMLrWU6o8c=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Giorgio',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 100,
                'Prezzo' => 190,
                'Indirizzo' => 'Via Dante, Bari, Italia',
                'Latitudine' => 41.117143,
                'Longitudine' => 16.871871,
                'Img' => 'https://media.istockphoto.com/id/1391264584/it/foto/parete-verde-chiaro-vuota-nel-soggiorno-moderno-mock-up-interni-in-stile-scandinavo-boho.jpg?s=612x612&w=0&k=20&c=2b-9blRbcI1asEYhUChIuRHIpWMVfVf0Wp1EQ4kpPx0=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Anna',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 80,
                'Prezzo' => 140,
                'Indirizzo' => 'Via Toledo, Napoli, Italia',
                'Latitudine' => 40.8517746,
                'Longitudine' => 14.2681244,
                'Img' => 'https://media.istockphoto.com/id/1423577767/it/foto/interni-moderni-del-soggiorno-con-divano-beige-porta-ad-arco-alla-sala-da-pranzo-rendering-3d.jpg?s=612x612&w=0&k=20&c=MmnAka07RO_6oeL7-Gmx5dSs1Jx0NxT1bchMIXAD_8A=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Aurora',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 140,
                'Prezzo' => 220,
                'Indirizzo' => 'Corso Umberto, Messina, Italia',
                'Latitudine' => 38.19381,
                'Longitudine' => 15.554,
                'Img' => 'https://media.istockphoto.com/id/1413964766/it/foto/rendering-3d-illustrazione-3d-scena-interna-e-mockup-camera-da-letto-di-rendering-del-designer.jpg?s=612x612&w=0&k=20&c=zo93fXaNuCUQXagYAy1BW2hfZAUxulYJeW3Po3a3P1g=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Riccardo',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 85,
                'Prezzo' => 150,
                'Indirizzo' => 'Via Garibaldi, Bologna, Italia',
                'Latitudine' => 44.494887,
                'Longitudine' => 11.342616,
                'Img' => 'https://media.istockphoto.com/id/1446453158/it/foto/wabi-sabi-interior-design-su-sfondo-parete-arco-concetto-di-mockup-da-parete-rendering-3d.jpg?s=612x612&w=0&k=20&c=fQk2YAbbw7KeT2UbMuKZGfYEdM6auUYy2s86lSK5jqQ=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa delle Rose',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 270,
                'Prezzo' => 400,
                'Indirizzo' => 'Via delle Rose, Lucca, Italia',
                'Latitudine' => 43.842393,
                'Longitudine' => 10.502695,
                'Img' => 'https://media.istockphoto.com/id/1284941011/it/foto/vista-interna-di-un-lussuoso-soggiorno-al-mare.jpg?s=612x612&w=0&k=20&c=a9iEJXD58EhvM0rIUnxP6JHKvwUaPI_g19BXVTcDfeY=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Giulia',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 75,
                'Prezzo' => 130,
                'Indirizzo' => 'Via Marina, Reggio Calabria, Italia',
                'Latitudine' => 38.114554,
                'Longitudine' => 15.650099,
                'Img' => 'https://media.istockphoto.com/id/1408488732/it/foto/soggiorno-in-stile-industriale-con-tavolo-da-pranzo-e-camino.jpg?s=612x612&w=0&k=20&c=D81KZZKdZgy1VraCYLkrFCn2bVhlUxRccThnrHFRMlg=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Loft Miramare',
                'Stanze' => 1,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 60,
                'Prezzo' => 120,
                'Indirizzo' => 'Via Trieste, Trieste, Italia',
                'Latitudine' => 45.649526,
                'Longitudine' => 13.776818,
                'Img' => 'https://media.istockphoto.com/id/1386951875/it/foto/zona-dininig-in-un-lussuoso-appartamento-in-rendering-3d.jpg?s=612x612&w=0&k=20&c=L95vXDTNmvO8MkOuz9e-KbF0LiKP5_jby7X7hy5unEE=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Elena',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 135,
                'Prezzo' => 240,
                'Indirizzo' => 'Via Fiume, Firenze, Italia',
                'Latitudine' => 43.76956,
                'Longitudine' => 11.255814,
                'Img' => 'https://media.istockphoto.com/id/1284706889/it/foto/una-stanza-con-un-albero-di-natale-decorato-con-giocattoli-regali-e-luci.jpg?s=612x612&w=0&k=20&c=ORCF2hrxfNet_wY_nntcV4psdqlWIEy_hdNVV-uwhrI=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Andrea',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 190,
                'Prezzo' => 290,
                'Indirizzo' => 'Via del Corso, Roma, Italia',
                'Latitudine' => 41.902783,
                'Longitudine' => 12.496366,
                'Img' => 'https://media.istockphoto.com/id/1405613825/it/foto/design-dinterni-del-soggiorno-vintage-creativo-e-moderno-con-divano-giallo-e-parete-a-lamelle.jpg?s=612x612&w=0&k=20&c=GQxWoUX5EFmywZfigS76SfAO9dVXBGtf-Tf4JOLvmRw=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Bianca',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 280,
                'Prezzo' => 400,
                'Indirizzo' => 'Via Vittorio Veneto, Palermo, Italia',
                'Latitudine' => 38.115687,
                'Longitudine' => 13.361267,

                'Img' => 'https://th.bing.com/th/id/R.5692d30c1db7dc013a266df79f4f5499?rik=z4JGhpg1jpA25w&pid=ImgRaw&r=0',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Carla',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 90,
                'Prezzo' => 150,
                'Indirizzo' => 'Via Dante, Catania, Italia',
                'Latitudine' => 37.507877,
                'Longitudine' => 15.08303,
                'Img' => 'https://media.istockphoto.com/id/1445482634/it/foto/lelegante-composizione-degli-interni-del-soggiorno-con-divano-beige-con-cuscino-plaid-tavolino.jpg?s=612x612&w=0&k=20&c=CPsZ08tfwK29tfxDUDVAlgtNzS20UbhKk_OU0v8zEew=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Paolo',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 140,
                'Prezzo' => 230,
                'Indirizzo' => 'Via San Carlo, Torino, Italia',
                'Latitudine' => 45.070312,
                'Longitudine' => 7.686856,
                'Img' => 'https://media.istockphoto.com/id/1366922971/it/foto/interni-domestici-con-accogliente-poltrona-e-credenza-mockup-del-soggiorno-rendering-3d.jpg?s=612x612&w=0&k=20&c=Vb6ThPx9udJ3NGVA9NzNQ1gKpjVRzQ00L8Od6DpE5P8=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Attico di Marta',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 180,
                'Prezzo' => 310,
                'Indirizzo' => 'Via Roma, Firenze, Italia',
                'Latitudine' => 43.76956,
                'Longitudine' => 11.255814,
                'Img' => 'https://media.istockphoto.com/id/1210123439/it/foto/classico-interno-grigio-con-poltrone-divano-tavolino-lampade-fiori-e-modanature-a-parete.jpg?s=612x612&w=0&k=20&c=EVaen69T6BsLLKkKJSpGv0eRjssyT41zy6GrVIIgZAM=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Aurora',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 100,
                'Prezzo' => 170,
                'Indirizzo' => 'Via Dante, Palermo, Italia',
                'Latitudine' => 38.115687,
                'Longitudine' => 13.361267,
                'Img' => 'https://media.istockphoto.com/id/1447133210/it/foto/design-moderno-degli-interni-di-un-accogliente-appartamento-soggiorno-con-poltrone-bianche.jpg?s=612x612&w=0&k=20&c=1G1odTAX-FuOi_vcbR3PHo-HeBf0FiYn7HrzAFumMTU=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Celeste',
                'Stanze' => 7,
                'Letti' => 6,
                'Bagni' => 5,
                'Metri_quadrati' => 300,
                'Prezzo' => 450,
                'Indirizzo' => 'Via San Marco, Pisa, Italia',
                'Latitudine' => 43.722838,
                'Longitudine' => 10.396629,
                'Img' => 'https://media.istockphoto.com/id/1366922971/it/foto/interni-domestici-con-accogliente-poltrona-e-credenza-mockup-del-soggiorno-rendering-3d.jpg?s=612x612&w=0&k=20&c=Vb6ThPx9udJ3NGVA9NzNQ1gKpjVRzQ00L8Od6DpE5P8=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Sergio',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 110,
                'Prezzo' => 200,
                'Indirizzo' => 'Via Carducci, Milano, Italia',
                'Latitudine' => 45.464211,
                'Longitudine' => 9.191383,
                'Img' => 'https://media.istockphoto.com/id/1334900941/it/foto/interni-moderni-di-un-ampio-soggiorno-in-3d.jpg?s=612x612&w=0&k=20&c=rHXH2oua1EZYRgZiJFZBHPlkU02gHm3tBuzB9aO_E84=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Rosa',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 130,
                'Prezzo' => 220,
                'Indirizzo' => 'Via Marina, Cagliari, Italia',
                'Latitudine' => 39.223841,
                'Longitudine' => 9.121661,
                'Img' => 'https://media.istockphoto.com/id/1217965544/it/foto/moderno-minimalismo-pesca-interni-con-divano-divano-piante-di-palma-e-tavolini-modello-di.jpg?s=612x612&w=0&k=20&c=BSzprf1wV7YpaK8M6y9DtgD0ptg3dcxlrHFC2GFQpvM=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Giacomo',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 80,
                'Prezzo' => 120,
                'Indirizzo' => 'Via Vittorio Emanuele, Siracusa, Italia',
                'Latitudine' => 37.075474,
                'Longitudine' => 15.286586,
                'Img' => 'https://media.istockphoto.com/id/1487766955/it/foto/il-luminoso-design-degli-interni-del-soggiorno-con-finestre-e-pareti-beige-%C3%A8-arredato-con.jpg?s=612x612&w=0&k=20&c=vWnwZSIj9biqgvIJlrFcBt5vvdDSbPdfoccmrgvSpA8=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa dei Fiori',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 220,
                'Prezzo' => 350,
                'Indirizzo' => 'Via Roma, Perugia, Italia',
                'Latitudine' => 43.1107,
                'Longitudine' => 12.39083,
                'Img' => 'https://media.istockphoto.com/id/1227624921/it/foto/sedie-in-legno-e-tavolo-su-sfondo-carta-da-parati-grigio-design-degli-interni-della-sala-da.jpg?s=612x612&w=0&k=20&c=Wno6mzVuRLWP-csoNmcfF6gARtf3PPjukP_jkueyI5E=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Laura',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 95,
                'Prezzo' => 140,
                'Indirizzo' => 'Via Libertà, Messina, Italia',
                'Latitudine' => 38.19381,
                'Longitudine' => 15.554,
                'Img' => 'https://media.istockphoto.com/id/1363806786/it/foto/composizione-moderna-di-elegante-design-degli-interni-del-soggiorno-con-cornice-del-poster.jpg?s=612x612&w=0&k=20&c=4pNCQT9xSG3DqeOqzjddVut_ozoMsF3EPp6AYK6qDME=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Giorgio',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 145,
                'Prezzo' => 240,
                'Indirizzo' => 'Via Roma, Genova, Italia',
                'Latitudine' => 44.40564,
                'Longitudine' => 8.946256,
                'Img' => 'https://media.istockphoto.com/id/1267663850/it/foto/interni-neri-con-divano-piante-e-tavolino-modello-di-illustrazione-di-rendering-3d.jpg?s=612x612&w=0&k=20&c=e6o2BHAN2ip66osJm0AVE9gkVGw8mYf8_0aP1a36sNc=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Elisa',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 110,
                'Prezzo' => 180,
                'Indirizzo' => 'Via Mazzini, Trieste, Italia',
                'Latitudine' => 45.649526,
                'Longitudine' => 13.776818,
                'Img' => 'https://media.istockphoto.com/id/1334880478/it/video/interior-empty-modern-loft-office-open-space-riprese-da-ufficio-moderne-moderno-concetto.jpg?s=640x640&k=20&c=boyN_50WcYA4-12qtPw42aIlhsIvlKqcJpSGmyLfSHU=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Attico di Marco',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 190,
                'Prezzo' => 300,
                'Indirizzo' => 'Via Vittorio Veneto, Firenze, Italia',
                'Latitudine' => 43.76956,
                'Longitudine' => 11.255814,
                'Img' => 'https://media.istockphoto.com/id/1446452504/it/foto/interior-design-minimalista-sullo-sfondo-della-parete-dellarco-concetto-di-mockup-da-parete.jpg?s=612x612&w=0&k=20&c=vgmPDruMEdocaMTZjkTS9PIi7YFVA3AE2Xejs8bNlJM=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Sofia',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 75,
                'Prezzo' => 130,
                'Indirizzo' => 'Via Marina, Livorno, Italia',
                'Latitudine' => 43.548473,
                'Longitudine' => 10.310567,
                'Img' => 'https://media.istockphoto.com/id/1446452504/it/foto/interior-design-minimalista-sullo-sfondo-della-parete-dellarco-concetto-di-mockup-da-parete.jpg?s=612x612&w=0&k=20&c=vgmPDruMEdocaMTZjkTS9PIi7YFVA3AE2Xejs8bNlJM=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Paradiso',
                'Stanze' => 8,
                'Letti' => 7,
                'Bagni' => 6,
                'Metri_quadrati' => 400,
                'Prezzo' => 500,
                'Indirizzo' => 'Via San Giorgio, Amalfi, Italia',
                'Latitudine' => 40.634574,
                'Longitudine' => 14.60205,
                'Img' => 'https://media.istockphoto.com/id/1335635511/it/video/timelapse-dellanimazione-di-rendering-3d-casa-interna-moderno-spazio-abitativo-aperto-con.jpg?s=640x640&k=20&c=8MNSNUXGziBmTeXuWCgAuLFR_GgUuI7wIoRf_xOmuLc=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Lorenzo',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 120,
                'Prezzo' => 200,
                'Indirizzo' => 'Via Garibaldi, Bari, Italia',
                'Latitudine' => 41.117143,
                'Longitudine' => 16.871871,
                'Img' => 'https://media.istockphoto.com/id/691429408/it/foto/interior-design-minimalista-soggiorno-verde-rendering-3d.jpg?s=612x612&w=0&k=20&c=GPJ0iHVH2Qh4X14xiMXBx42hwSUH2huEUYu98AL-YQU=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Simona',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 85,
                'Prezzo' => 160,
                'Indirizzo' => 'Via San Paolo, Verona, Italia',
                'Latitudine' => 45.438759,
                'Longitudine' => 10.99162,
                'Img' => 'https://media.istockphoto.com/id/1469812453/it/foto/interior-design-di-appartamento-moderno-soggiorno-con-divano-nero-sopra-il-muro-di-piastrelle.jpg?s=612x612&w=0&k=20&c=PmbqjUQwRozvlWY4VRGAF32l50d_GueQoWKgqkvDkZE=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Filippo',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 175,
                'Prezzo' => 280,
                'Indirizzo' => 'Via Dante, Torino, Italia',
                'Latitudine' => 45.070312,
                'Longitudine' => 7.686856,
                'Img' => 'https://media.istockphoto.com/id/1470717532/it/foto/interno-di-casa-moderna.jpg?s=612x612&w=0&k=20&c=1R1iVGFaVlW1Iu4C0fxAEza6kSNIVLK2O9Cwy7fzJ-E=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa dei Cipressi',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 270,
                'Prezzo' => 420,
                'Indirizzo' => 'Via dei Cipressi, Siena, Italia',
                'Latitudine' => 43.318809,
                'Longitudine' => 11.330757,
                'Img' => 'https://media.istockphoto.com/id/1384260565/it/foto/composizione-elegante-di-interni-moderni-del-soggiorno-mock-up-cornice-poster-divano-moderno.jpg?s=612x612&w=0&k=20&c=OXK_UxaIveRp6c3_iGN4rQhSMunicWyMtv4s45hY4jU=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Martina',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 90,
                'Prezzo' => 150,
                'Indirizzo' => 'Via San Francesco, Trento, Italia',
                'Latitudine' => 46.074779,
                'Longitudine' => 11.121748,
                'Img' => 'https://media.istockphoto.com/id/1285242397/it/foto/immagine-generata-digitalmente-di-un-appartamento-loft-in-stile-industriale.jpg?s=612x612&w=0&k=20&c=k6XqJq0xyQLnBO6ausjU3EIn8JwSYW_Chp6iSewnwSQ=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Antonio',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 120,
                'Prezzo' => 200,
                'Indirizzo' => 'Via Libertà, Lecce, Italia',
                'Latitudine' => 40.351515,
                'Longitudine' => 18.174366,
                'Img' => 'https://media.istockphoto.com/id/1288806002/it/foto/soggiorno-completamente-arredato-di-un-appartamento.jpg?s=612x612&w=0&k=20&c=8LaBoH7yvp44Yxp_1-vkFp9mLrm1w6xA4SlJOuWVpdg=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Valeria',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 70,
                'Prezzo' => 110,
                'Indirizzo' => 'Via Firenze, Bologna, Italia',
                'Latitudine' => 44.494887,
                'Longitudine' => 11.342616,
                'Img' => 'https://media.istockphoto.com/id/892550490/it/foto/moderno-design-degli-interni-loft.jpg?s=612x612&w=0&k=20&c=ID3q8Z3jit7e-xE9FxWMRa27uOho5xdGT4raIKY0g2w=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Claudia',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 105,
                'Prezzo' => 170,
                'Indirizzo' => 'Via Garibaldi, Pisa, Italia',
                'Latitudine' => 43.722838,
                'Longitudine' => 10.396629,
                'Img' => 'https://media.istockphoto.com/id/1442716898/it/foto/design-moderno-degli-interni-di-un-accogliente-appartamento-soggiorno-con-divano-beige.jpg?s=612x612&w=0&k=20&c=9QkJ00_QiTkbPbVoYUu_dUhqIwy382pIltqmFJnJ3vM=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Loft Sole',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 75,
                'Prezzo' => 130,
                'Indirizzo' => 'Via Roma, Sassari, Italia',
                'Latitudine' => 40.727504,
                'Longitudine' => 8.558167,
                'Img' => 'https://media.istockphoto.com/id/678464714/it/foto/piatto-con-decori-gialli.jpg?s=612x612&w=0&k=20&c=y1VCxqpgVyM8qYyFnh_UM4mnJgm5xdpmyzohuUVYo1o=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Chiara',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 140,
                'Prezzo' => 240,
                'Indirizzo' => 'Via Garibaldi, Trapani, Italia',
                'Latitudine' => 38.01778,
                'Longitudine' => 12.536842,
                'Img' => 'https://a0.muscache.com/pictures/6b918aad-3492-469c-acbd-5bd093f83aea.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa delle Palme',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 250,
                'Prezzo' => 380,
                'Indirizzo' => 'Via delle Palme, Catania, Italia',
                'Latitudine' => 37.507877,
                'Longitudine' => 15.08303,
                'Img' => 'https://media.istockphoto.com/id/1125385998/it/foto/interni-di-lusso-e-moderni-per-la-casa-con-mobili-di-design-poltrona-tavoli-pouf-e-accessi-un.jpg?s=612x612&w=0&k=20&c=tXOFf0kg1uZIXJrcur-T1h0p4Hc6YOblGlmvS3FJh1g=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Federica',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 100,
                'Prezzo' => 160,
                'Indirizzo' => 'Via Dante, Napoli, Italia',
                'Latitudine' => 40.8517746,
                'Longitudine' => 14.2681244,
                'Img' => 'https://media.istockphoto.com/id/1130536041/it/foto/interni-eleganti-e-vintage-con-mobili-classici-in-legno-divano-grigio-tavolino-retr%C3%B2-lampada-e.jpg?s=612x612&w=0&k=20&c=3sL70Fp7VlDJitH_aKyjVJup1arSIY7Prygpq1jhM5Y=',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Alessandro',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 190,
                'Prezzo' => 300,
                'Indirizzo' => 'Via Firenze, Roma, Italia',
                'Latitudine' => 41.902783,
                'Longitudine' => 12.496366,
                'Img' => 'https://th.bing.com/th/id/R.4f864f8484c755e29ab9692faa746409?rik=7zVtJTjeOcZ9Ew&pid=ImgRaw&r=0',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Giorgia',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 85,
                'Prezzo' => 150,
                'Indirizzo' => 'Via San Michele, Siena, Italia',
                'Latitudine' => 43.318809,
                'Longitudine' => 11.330757,
                'Img' => 'https://media.istockphoto.com/id/1357529184/it/foto/rendering-3d-di-un-interno-contemporaneo-del-soggiorno.jpg?s=612x612&w=0&k=20&c=SXPwpZwnTbq3CbczmmUtgisjXyvMOdcWu6KOLhuXzVk=',
                'Visibilità' => true,
            ]
        ];

        $users= User::all()->pluck('id');

        foreach($apartmentsData as $apartment) {
            $newApartment = New Apartment();
            $newApartment -> user_id = fake()->randomElement($users);
            $newApartment -> nome = $apartment['Nome'];
            $newApartment -> stanze = $apartment['Stanze'];
            $newApartment -> letti = $apartment['Letti'];
            $newApartment -> bagni = $apartment['Bagni'];
            $newApartment -> metri_quadrati = $apartment['Metri_quadrati'];
            $newApartment -> prezzo = $apartment['Prezzo'];
            $newApartment -> indirizzo = $apartment['Indirizzo'];
            $newApartment -> latitudine = $apartment['Latitudine'];
            $newApartment -> longitudine = $apartment['Longitudine'];
            $newApartment -> img = $apartment['Img'];
            $newApartment -> visibilità = $apartment['Visibilità'];
            $newApartment -> save();
        }
    }
}
