<?php

namespace Database\Seeders;

use App\Models\Apartment;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ApartmentSeeder extends Seeder
{
    public function run()
    {

        $apartmentsData=[


            [
                'Nome' => 'Appartamento Milano',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 75,
                'Prezzo' => 100,
                'Indirizzo' => 'Via Giovanni Boccaccio, 12, Cologno Monzese, MI, Italia',
                'Latitudine' => 45.46368,
                'Longitudine' => 9.18841,
                'Img' => "https://cf.bstatic.com/xdata/images/hotel/max1280x900/282045872.jpg?k=e4d2a3117babf76d7b185c308c40988b89bab8d720bfec0c8b77aa901032580e&o=&hp=1",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Napoli',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 100,
                'Prezzo' => 120,
                'Indirizzo' => 'Via Toledo, Via dei Tribunali, Napoli, NA, Italia',
                'Latitudine' => 40.851798,
                'Longitudine' => 14.26812,
                'Img' => "https://st.hzcdn.com/simgs/pictures/soggiorni/home-staging-appartamento-vuoto-in-vendita-micro-interior-design-img~503160220ccd6834_4-8587-1-f5ce958.jpg",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Firenze',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 60,
                'Prezzo' => 90,
                'Indirizzo' => 'Via Palagio degli Spini, Firenze, FI, Italia',
                'Latitudine' => 43.769871,
                'Longitudine' => 11.255576,
                'Img' => "https://st3.idealista.it/news/archivie/styles/fullwidth_xl/public/2016-08/casa-ensueno-brasil12.jpg?VersionId=jgSaLtFxa1yzA8WKrjyvyrDKtTfVAivq&itok=zYIiAsr8",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Torino',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 150,
                'Prezzo' => 150,
                'Indirizzo' => 'Via Giuseppe Garibaldi, Torino, TO, Italia',
                'Latitudine' => 45.070339,
                'Longitudine' => 7.686864,
                'Img' => "https://cf.bstatic.com/xdata/images/hotel/max1280x900/586882190.jpg?k=54c3827fe253828c127f9f8acf6e72e76deb78a46f1cf440e5ea2c77e3225288&o=&hp=1",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Roma',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 2,
                'Metri_quadrati' => 85,
                'Prezzo' => 110,
                'Indirizzo' => 'Via Appia Antica, Roma RM, Italia',
                'Latitudine' => 41.902784,
                'Longitudine' => 12.496366,
                'Img' => 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/489162690.jpg?k=7e671114aa511d795b7b65b81c7351ee25ed50898891c5cb1f16a8996e08ba44&o=&hp=1',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Genova',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 55,
                'Prezzo' => 85,
                'Indirizzo' => 'Via XX Settembre, Genova, GE, Italia',
                'Latitudine' => 44.407062,
                'Longitudine' => 8.93399,
                'Img' => "https://cf.bstatic.com/xdata/images/hotel/max1280x900/562717787.jpg?k=58d2a48b7e8f0e573bc607a544bc4e9188facf22d5f6d8409980de2b8f8f621a&o=&hp=1",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Venezia',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 120,
                'Prezzo' => 200,
                'Indirizzo' => 'Via Santa Lucia, Venezia, VE, Italia',
                'Latitudine' => 45.434046,
                'Longitudine' => 12.338166,
                'Img' => "https://c8.alamy.com/compit/2wacc5b/la-rovina-dell-edificio-abbandonato-sta-crollando-la-casa-residenziale-con-piu-appartamenti-e-in-pessime-condizioni-la-poverta-nella-zona-di-confine-e-evidente-2wacc5b.jpg",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Palermo',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 70,
                'Prezzo' => 80,
                'Indirizzo' => 'Via Maqueda, Palermo, PA, Italia',
                'Latitudine' => 38.115697,
                'Longitudine' => 13.361267,
                'Img' => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmZB3HScZuVqpr-tdK1EMdyyTF5fNAKTmdNQ&s",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Bari',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 2,
                'Metri_quadrati' => 95,
                'Prezzo' => 95,
                'Indirizzo' => 'Via Giuseppe Capruzzi, Bari BA, Italia',
                'Latitudine' => 41.125594,
                'Longitudine' => 16.866067,
                'Img' => "https://cf.bstatic.com/xdata/images/hotel/max1280x900/279242261.jpg?k=adc7fae710c77d0d15cb7c8451d8ac088b7e51104db0d895c0a09c63ded20ba6&o=&hp=1",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Verona',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 160,
                'Prezzo' => 180,
                'Indirizzo' => 'Via del Pestrino, Verona, Italia',
                'Latitudine' => 45.438759,
                'Longitudine' => 10.99162,
                'Img' => "https://www.grazia.it/content/uploads/2017/10/cover-piante-appartamento-mobile-800x600.jpg",
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Marco',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 120,
                'Prezzo' => 180,
                'Indirizzo' => 'Via della Libertà, Palermo, Italia',
                'Latitudine' => 38.12445,
                'Longitudine' => 13.35732,
                'Img' => 'https://example.com/img1.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Alessandra',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 85,
                'Prezzo' => 160,
                'Indirizzo' => 'Via del Corso, Roma, Italia',
                'Latitudine' => 41.902783,
                'Longitudine' => 12.496366,
                'Img' => 'https://example.com/img2.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Attico Aurora',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 180,
                'Prezzo' => 270,
                'Indirizzo' => 'Via Torino, Milano, Italia',
                'Latitudine' => 45.464211,
                'Longitudine' => 9.191383,
                'Img' => 'https://example.com/img3.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Arcobaleno',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 250,
                'Prezzo' => 350,
                'Indirizzo' => 'Via Garibaldi, Venezia, Italia',
                'Latitudine' => 45.437191,
                'Longitudine' => 12.334589,
                'Img' => 'https://example.com/img4.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Luca',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 95,
                'Prezzo' => 140,
                'Indirizzo' => 'Via XX Settembre, Genova, Italia',
                'Latitudine' => 44.40564,
                'Longitudine' => 8.946256,
                'Img' => 'https://example.com/img5.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa Sole',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 110,
                'Prezzo' => 210,
                'Indirizzo' => 'Via Roma, Cagliari, Italia',
                'Latitudine' => 39.223841,
                'Longitudine' => 9.121661,
                'Img' => 'https://example.com/img6.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Gaia',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 70,
                'Prezzo' => 120,
                'Indirizzo' => 'Via Dante, Bari, Italia',
                'Latitudine' => 41.117143,
                'Longitudine' => 16.871871,
                'Img' => 'https://example.com/img7.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Loft Stella',
                'Stanze' => 1,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 60,
                'Prezzo' => 130,
                'Indirizzo' => 'Via Mazzini, Torino, Italia',
                'Latitudine' => 45.070312,
                'Longitudine' => 7.686856,
                'Img' => 'https://example.com/img8.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Federico',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 125,
                'Prezzo' => 230,
                'Indirizzo' => 'Piazza San Marco, Venezia, Italia',
                'Latitudine' => 45.434095,
                'Longitudine' => 12.338844,
                'Img' => 'https://example.com/img9.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Attico di Martina',
                'Stanze' => 6,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 200,
                'Prezzo' => 320,
                'Indirizzo' => 'Via San Lorenzo, Firenze, Italia',
                'Latitudine' => 43.76956,
                'Longitudine' => 11.255814,
                'Img' => 'https://example.com/img10.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Luna',
                'Stanze' => 7,
                'Letti' => 6,
                'Bagni' => 5,
                'Metri_quadrati' => 300,
                'Prezzo' => 450,
                'Indirizzo' => 'Via Vittorio Emanuele, Palermo, Italia',
                'Latitudine' => 38.115687,
                'Longitudine' => 13.361267,
                'Img' => 'https://example.com/img11.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Giorgio',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 100,
                'Prezzo' => 190,
                'Indirizzo' => 'Via Dante, Bari, Italia',
                'Latitudine' => 41.117143,
                'Longitudine' => 16.871871,
                'Img' => 'https://example.com/img12.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Anna',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 80,
                'Prezzo' => 140,
                'Indirizzo' => 'Via Toledo, Napoli, Italia',
                'Latitudine' => 40.8517746,
                'Longitudine' => 14.2681244,
                'Img' => 'https://example.com/img13.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Aurora',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 140,
                'Prezzo' => 220,
                'Indirizzo' => 'Corso Umberto, Messina, Italia',
                'Latitudine' => 38.19381,
                'Longitudine' => 15.554,
                'Img' => 'https://example.com/img14.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Riccardo',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 85,
                'Prezzo' => 150,
                'Indirizzo' => 'Via Garibaldi, Bologna, Italia',
                'Latitudine' => 44.494887,
                'Longitudine' => 11.342616,
                'Img' => 'https://example.com/img15.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa delle Rose',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 270,
                'Prezzo' => 400,
                'Indirizzo' => 'Via delle Rose, Lucca, Italia',
                'Latitudine' => 43.842393,
                'Longitudine' => 10.502695,
                'Img' => 'https://example.com/img16.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Giulia',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 75,
                'Prezzo' => 130,
                'Indirizzo' => 'Via Marina, Reggio Calabria, Italia',
                'Latitudine' => 38.114554,
                'Longitudine' => 15.650099,
                'Img' => 'https://example.com/img17.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Loft Miramare',
                'Stanze' => 1,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 60,
                'Prezzo' => 120,
                'Indirizzo' => 'Via Trieste, Trieste, Italia',
                'Latitudine' => 45.649526,
                'Longitudine' => 13.776818,
                'Img' => 'https://example.com/img18.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Elena',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 135,
                'Prezzo' => 240,
                'Indirizzo' => 'Via Fiume, Firenze, Italia',
                'Latitudine' => 43.76956,
                'Longitudine' => 11.255814,
                'Img' => 'https://example.com/img19.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Andrea',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 190,
                'Prezzo' => 290,
                'Indirizzo' => 'Via del Corso, Roma, Italia',
                'Latitudine' => 41.902783,
                'Longitudine' => 12.496366,
                'Img' => 'https://example.com/img20.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Bianca',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 280,
                'Prezzo' => 400,
                'Indirizzo' => 'Via Vittorio Veneto, Palermo, Italia',
                'Latitudine' => 38.115687,
                'Longitudine' => 13.361267,
                'Img' => 'https://example.com/img21.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Carla',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 90,
                'Prezzo' => 150,
                'Indirizzo' => 'Via Dante, Catania, Italia',
                'Latitudine' => 37.507877,
                'Longitudine' => 15.08303,
                'Img' => 'https://example.com/img22.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Paolo',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 140,
                'Prezzo' => 230,
                'Indirizzo' => 'Via San Carlo, Torino, Italia',
                'Latitudine' => 45.070312,
                'Longitudine' => 7.686856,
                'Img' => 'https://example.com/img23.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Attico di Marta',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 180,
                'Prezzo' => 310,
                'Indirizzo' => 'Via Roma, Firenze, Italia',
                'Latitudine' => 43.76956,
                'Longitudine' => 11.255814,
                'Img' => 'https://example.com/img24.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Aurora',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 100,
                'Prezzo' => 170,
                'Indirizzo' => 'Via Dante, Palermo, Italia',
                'Latitudine' => 38.115687,
                'Longitudine' => 13.361267,
                'Img' => 'https://example.com/img25.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Celeste',
                'Stanze' => 7,
                'Letti' => 6,
                'Bagni' => 5,
                'Metri_quadrati' => 300,
                'Prezzo' => 450,
                'Indirizzo' => 'Via San Marco, Pisa, Italia',
                'Latitudine' => 43.722838,
                'Longitudine' => 10.396629,
                'Img' => 'https://example.com/img26.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Sergio',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 110,
                'Prezzo' => 200,
                'Indirizzo' => 'Via Carducci, Milano, Italia',
                'Latitudine' => 45.464211,
                'Longitudine' => 9.191383,
                'Img' => 'https://example.com/img27.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento Rosa',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 130,
                'Prezzo' => 220,
                'Indirizzo' => 'Via Marina, Cagliari, Italia',
                'Latitudine' => 39.223841,
                'Longitudine' => 9.121661,
                'Img' => 'https://example.com/img28.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Giacomo',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 80,
                'Prezzo' => 120,
                'Indirizzo' => 'Via Vittorio Emanuele, Siracusa, Italia',
                'Latitudine' => 37.075474,
                'Longitudine' => 15.286586,
                'Img' => 'https://example.com/img29.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa dei Fiori',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 220,
                'Prezzo' => 350,
                'Indirizzo' => 'Via Roma, Perugia, Italia',
                'Latitudine' => 43.1107,
                'Longitudine' => 12.39083,
                'Img' => 'https://example.com/img30.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Laura',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 95,
                'Prezzo' => 140,
                'Indirizzo' => 'Via Libertà, Messina, Italia',
                'Latitudine' => 38.19381,
                'Longitudine' => 15.554,
                'Img' => 'https://example.com/img31.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Giorgio',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 145,
                'Prezzo' => 240,
                'Indirizzo' => 'Via Roma, Genova, Italia',
                'Latitudine' => 44.40564,
                'Longitudine' => 8.946256,
                'Img' => 'https://example.com/img32.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Elisa',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 110,
                'Prezzo' => 180,
                'Indirizzo' => 'Via Mazzini, Trieste, Italia',
                'Latitudine' => 45.649526,
                'Longitudine' => 13.776818,
                'Img' => 'https://example.com/img33.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Attico di Marco',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 190,
                'Prezzo' => 300,
                'Indirizzo' => 'Via Vittorio Veneto, Firenze, Italia',
                'Latitudine' => 43.76956,
                'Longitudine' => 11.255814,
                'Img' => 'https://example.com/img34.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Sofia',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 75,
                'Prezzo' => 130,
                'Indirizzo' => 'Via Marina, Livorno, Italia',
                'Latitudine' => 43.548473,
                'Longitudine' => 10.310567,
                'Img' => 'https://example.com/img35.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa Paradiso',
                'Stanze' => 8,
                'Letti' => 7,
                'Bagni' => 6,
                'Metri_quadrati' => 400,
                'Prezzo' => 500,
                'Indirizzo' => 'Via San Giorgio, Amalfi, Italia',
                'Latitudine' => 40.634574,
                'Longitudine' => 14.60205,
                'Img' => 'https://example.com/img36.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Lorenzo',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 120,
                'Prezzo' => 200,
                'Indirizzo' => 'Via Garibaldi, Bari, Italia',
                'Latitudine' => 41.117143,
                'Longitudine' => 16.871871,
                'Img' => 'https://example.com/img37.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Simona',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 85,
                'Prezzo' => 160,
                'Indirizzo' => 'Via San Paolo, Verona, Italia',
                'Latitudine' => 45.438759,
                'Longitudine' => 10.99162,
                'Img' => 'https://example.com/img38.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Filippo',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 175,
                'Prezzo' => 280,
                'Indirizzo' => 'Via Dante, Torino, Italia',
                'Latitudine' => 45.070312,
                'Longitudine' => 7.686856,
                'Img' => 'https://example.com/img39.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa dei Cipressi',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 270,
                'Prezzo' => 420,
                'Indirizzo' => 'Via dei Cipressi, Siena, Italia',
                'Latitudine' => 43.318809,
                'Longitudine' => 11.330757,
                'Img' => 'https://example.com/img40.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Martina',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 90,
                'Prezzo' => 150,
                'Indirizzo' => 'Via San Francesco, Trento, Italia',
                'Latitudine' => 46.074779,
                'Longitudine' => 11.121748,
                'Img' => 'https://example.com/img41.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Antonio',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 120,
                'Prezzo' => 200,
                'Indirizzo' => 'Via Libertà, Lecce, Italia',
                'Latitudine' => 40.351515,
                'Longitudine' => 18.174366,
                'Img' => 'https://example.com/img42.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Valeria',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 70,
                'Prezzo' => 110,
                'Indirizzo' => 'Via Firenze, Bologna, Italia',
                'Latitudine' => 44.494887,
                'Longitudine' => 11.342616,
                'Img' => 'https://example.com/img43.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Claudia',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 105,
                'Prezzo' => 170,
                'Indirizzo' => 'Via Garibaldi, Pisa, Italia',
                'Latitudine' => 43.722838,
                'Longitudine' => 10.396629,
                'Img' => 'https://example.com/img44.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Loft Sole',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 75,
                'Prezzo' => 130,
                'Indirizzo' => 'Via Roma, Sassari, Italia',
                'Latitudine' => 40.727504,
                'Longitudine' => 8.558167,
                'Img' => 'https://example.com/img45.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Chiara',
                'Stanze' => 4,
                'Letti' => 3,
                'Bagni' => 2,
                'Metri_quadrati' => 140,
                'Prezzo' => 240,
                'Indirizzo' => 'Via Garibaldi, Trapani, Italia',
                'Latitudine' => 38.01778,
                'Longitudine' => 12.536842,
                'Img' => 'https://example.com/img46.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Villa delle Palme',
                'Stanze' => 6,
                'Letti' => 5,
                'Bagni' => 4,
                'Metri_quadrati' => 250,
                'Prezzo' => 380,
                'Indirizzo' => 'Via delle Palme, Catania, Italia',
                'Latitudine' => 37.507877,
                'Longitudine' => 15.08303,
                'Img' => 'https://example.com/img47.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Federica',
                'Stanze' => 3,
                'Letti' => 2,
                'Bagni' => 1,
                'Metri_quadrati' => 100,
                'Prezzo' => 160,
                'Indirizzo' => 'Via Dante, Napoli, Italia',
                'Latitudine' => 40.8517746,
                'Longitudine' => 14.2681244,
                'Img' => 'https://example.com/img48.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Appartamento di Alessandro',
                'Stanze' => 5,
                'Letti' => 4,
                'Bagni' => 3,
                'Metri_quadrati' => 190,
                'Prezzo' => 300,
                'Indirizzo' => 'Via Firenze, Roma, Italia',
                'Latitudine' => 41.902783,
                'Longitudine' => 12.496366,
                'Img' => 'https://example.com/img49.jpg',
                'Visibilità' => true,
            ],
            [
                'Nome' => 'Casa di Giorgia',
                'Stanze' => 2,
                'Letti' => 1,
                'Bagni' => 1,
                'Metri_quadrati' => 85,
                'Prezzo' => 150,
                'Indirizzo' => 'Via San Michele, Siena, Italia',
                'Latitudine' => 43.318809,
                'Longitudine' => 11.330757,
                'Img' => 'https://example.com/img50.jpg',
                'Visibilità' => true,
            ]
        ];

        $users= User::all()->pluck('id');

        foreach($apartmentsData as $apartment) {
            $newApartment = New Apartment();
            $newApartment -> user_id = fake()->randomElement($users);
            $newApartment -> nome = $apartment['Nome'];
            $newApartment -> stanze = $apartment['Stanze'];
            $newApartment -> letti = $apartment['Letti'];
            $newApartment -> bagni = $apartment['Bagni'];
            $newApartment -> metri_quadrati = $apartment['Metri_quadrati'];
            $newApartment -> prezzo = $apartment['Prezzo'];
            $newApartment -> indirizzo = $apartment['Indirizzo'];
            $newApartment -> latitudine = $apartment['Latitudine'];
            $newApartment -> longitudine = $apartment['Longitudine'];
            $newApartment -> img = $apartment['Img'];
            $newApartment -> visibilità = $apartment['Visibilità'];
            $newApartment -> save();
        }
    }
}
